### ISSUE TITLE
Open discussion and debug on alfhv's fork and source generator usage

### ISSUE THREAD

**Issue by alfhv** [alexrosenfeld10/avro-sourcegen-csharp#2]
commenting here to dont pollute anymore the official Avro repo with our issues.
please can you check if enum namespace is correct ??

the type referenced here is : Space.Models.**Planet**.PlanetEnum
```
"name": "Planets",
      "type": {
        "type": "array",
        "items": "Space.Models.Planet.PlanetEnum"
      }
```

bon the type is: Space.Models.PlanetEnum
```
  "name": "PlanetEnum",
  "namespace": "Space.Models",
  "type": "enum",
```

can you check on it ??

**Comment by alexrosenfeld10** [comment]
Yes, it's [just a typo](https://github.com/alexrosenfeld10/avro-sourcegen-csharp/commit/f774176803c4a94b26b2823506a2f816c6d4650c#r112092981), sorry. I fixed in the latest commits..  did you see #1 ? It uses your fork, and works successfully. Check the PR for more details.

**Comment by alfhv** [comment]
good it works for you, just a question, for me there is a bug/issue on my code.
when several files are loaded, it should be done in the good order, respecting the references (thats why I use OrderBy() )
in your case, if you rename planet-enum.json to zzplanet-enum.json it should fail as the enum Type is not yet loaded when it is referenced.
can you confirm this happens to you also ?

**Comment by alexrosenfeld10** [comment]
I'll test it out when I next get the chance. I agree, it should have order-agnostic resolution, especially if the intent is to merge into apache.

I would also like to add the ability to return the generated code as a string, instead of forcing to write to files. I'll look at adding that

**Comment by alexrosenfeld10** [comment]
@alfhv yeah, when I rename to `zzzplanet-enum.json` to force a bad ordering I get:

```
CSC : warning CS8785: Generator 'AvroGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. 
Exception was of type 'SchemaParseException' with message
'Undefined name: Space.Models.PlanetEnum at 'fields[1].type.items'' [/Users/arosenfeld/dev/repos/avro-sourcegen-csharp/GeneratedModels/GeneratedModels.csproj]
```

**Comment by alexrosenfeld10** [comment]
@alfhv please find the PR to directly return types, instead of writing to disk: https://github.com/alfhv/avro/pull/2
